config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root "links#index"
  resources :links
  get ':slug' => 'links#show'

end

app/models/link.rb
class Link < ActiveRecord::Base

	belongs_to :user

	after_create :generate_slug, :scrape_title

	validates :url, :url => true, :presence => true

	def generate_slug
    	self.slug = self.id.to_s(36)
    	self.save
  	end

  	def scrape_title
	    self.title = Mechanize.new.get(self.url).title
	    self.save
  	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :set_link, only: [:destroy]

  # GET /links
  # GET /links.json
  def index
    if user_signed_in?
      @links = Link.all.joins(:user).where('users.email' => current_user.email).order(created_at: :desc).paginate(:page => params[:page], :per_page => 5)
    else
      render "home"
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    if params[:slug]
      # if there is slug in the URL, find the Link inside database with that slug
      @link = Link.find_by(slug: params[:slug])
      if @link
        # and redirect the request to the Link original URL
        redirect_to @link.url
      else
        # else, just show the Link details page
        redirect_to root_path
      end
    else
      @link = Link.find(params[:id])
    end
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)
    @link.user_id = current_user.id
    
    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    if @link.user.email == current_user.email
      @link.destroy
      respond_to do |format|
        format.html { redirect_to root_url, notice: 'Link was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:url, users_attributes: [:user_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>URL Shortener</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "URL Shortener", root_url, class: "navbar-brand" %>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	      	<% if user_signed_in? %>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
		          <ul class="dropdown-menu">
		            <li><%= link_to edit_user_registration_url do %>Edit profile<% end %></li>
		            <li role="separator" class="divider"></li>
		            <li><%= link_to destroy_user_session_path, method: :delete do %>Logout<% end %></li>
		          </ul>
		        </li>
		    <% else %>
		    	<form class="navbar-form navbar-right auth-btn">
		    	<%= link_to new_user_session_url, class: "btn btn-success" do %>Sign in<% end %>
				<%= link_to new_user_registration_url, class: "btn btn-primary" do %>Sign up<% end %>
				</form>
	        <% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<div class="container">
		
		<% flash.each do |key, value| %>
		  	<div class="alert alert-info">
		      <%= value %>
		    </div>
		  <% end %>

		<%= yield %>
			
	</div>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :url, "URL" %><br>
    <%= f.url_field :url, class: "form-control", placeholder: "Eg: http://google.com" %>
    <p class="help-block">Make sure you enter a valid URL with <i>http://</i> or <i>https://</i></p>
  </div>

  <div class="form-group">
    <%= f.button :submit, class: "btn btn-primary" do %>
      Shorten URL
    <% end %>
    <%= link_to 'Back', root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/links/home.html.erb
<center>
	<h2>Welcome to my URL Shortener app!</h2>
</center>
<center>
	<h3>Please sign in to shorten your links.</h3>
</center>

app/views/links/index.html.erb
<h3>Your Links</h3>
<div class="row">
  <div class="col-md-12">

    <% if user_signed_in? %>
      <%= link_to 'Add New Link', new_link_path, class: "btn btn-primary" %>
    <% end %>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Shortened URL</th>
          <th>Open URL</th>
          <% if user_signed_in? %>
            <th style="text-align: center;">Action</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @links.each do |link| %>
          <tr>
            <td>
              <% if link.title.present? %>
                <%= link.title %>
              <% else %>
                <span>-</span>
              <% end %>
            </td>
            <td><%= request.base_url + "/" + link.slug %></td>
            <td><%= link_to "Open URL", request.base_url + "/" + link.slug, target: "_blank", class: "btn btn-success" %></td>
            <% if user_signed_in? %>
              <td><%= link_to 'Delete', link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @links, renderer: BootstrapPagination::Rails %>

  </div> <!-- /col-md-12 -->
</div> <!-- /row -->

app/views/links/new.html.erb
<h3>New Link</h3>

<div class="row">
	<div class="col-md-4">
		<%= render 'form' %>
	</div> <!-- /col-md-4 -->
</div> <!-- /row -->

app/views/links/show.html.erb
<div class="row">
	<div class="col-md-6">

		<p>
		  <strong>URL:</strong><br>
		  <%= @link.url %>
		</p>

		<p>
		  <strong>Shortened URL:</strong><br>
		  <%= request.base_url + "/" + @link.slug %>
		</p>

		<% if @link.title.present? %>
			<p>
			  <strong>Title:</strong><br>
			  <%= @link.title %>
			</p>
		<% end %>

		<%= link_to "Open URL", request.base_url + "/" + @link.slug, target: "_blank", class: "btn btn-success" %> <%= link_to 'Back', root_path, class: "btn btn-default" %>
	</div> <!-- /col-md-6 -->
</div> <!-- /row -->